spring:
    application:
        name: address-service
    datasource:
        url: jdbc:mysql://localhost:3306/microservices
        username: root
        password: root
    jpa:
        show-sql: true
server:
    port: 8081
    servlet:
        context-path: /address-service