spring:
    application:
        name: employee-service
    datasource:
        url: jdbc:mysql://localhost:3306/microservices
        username: root
        password: root
    jpa:
        show-sql: true
server:
    port: 8080
    servlet:
        context-path: /employee-service